[package]
name = "varvara"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = { version = "0.25", optional = true }
static_assertions = "1.1.0"
zerocopy = { version = "0.7.34", features = ["derive"] }

uxn.path = "../uxn"

[features]
default = ["screen"]
screen = ["dep:minifb"]
